/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jni_Sample */

#ifndef _Included_jni_Sample
#define _Included_jni_Sample
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jni_Sample
 * Method:    intMethod
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_jni_Sample_intMethod
  (JNIEnv *, jobject, jint);

/*
 * Class:     jni_Sample
 * Method:    booleanMethod
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_jni_Sample_booleanMethod
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     jni_Sample
 * Method:    stringMethod
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jni_Sample_stringMethod
  (JNIEnv *, jobject, jstring);

/*
 * Class:     jni_Sample
 * Method:    intArrayMethod
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_jni_Sample_intArrayMethod
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     jni_Sample
 * Method:    arrayOfArray
 * Signature: ()Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_jni_Sample_arrayOfArray
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
